"""Agregar campo orden a tabla imagenes y actualizar relaciones

Revision ID: 167eba4a4c5b
Revises: e0ea8222558e
Create Date: 2026-09-29 23:03:39.786278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167eba4a4c5b'
down_revision = 'e0ea8222558e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('k_producto',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('k_producto',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
