"""items de solicitud, nota de cotizacion y item con lanzamiento opcional

Revision ID: 20d924a3b851
Revises: 0e611090a42f
Create Date: 2026-10-02 10:12:56.877398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d924a3b851'
down_revision = '0e611090a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_solicitud', sa.Integer(), nullable=False),
    sa.Column('k_producto', sa.Integer(), nullable=True),
    sa.Column('k_lanzamiento', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('cantidad', sa.Integer(), server_default='1', nullable=False),
    sa.Column('precio_unit', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['k_lanzamiento'], ['lanzamiento.id'], name=op.f('fk_solicitud_item_k_lanzamiento_lanzamiento')),
    sa.ForeignKeyConstraint(['k_producto'], ['producto.id'], name=op.f('fk_solicitud_item_k_producto_producto')),
    sa.ForeignKeyConstraint(['k_solicitud'], ['solicitud.id'], name=op.f('fk_solicitud_item_k_solicitud_solicitud')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitud_item'))
    )
    with op.batch_alter_table('solicitud_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitud_item_k_solicitud'), ['k_solicitud'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_lanzamiento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('n_item', sa.String(length=150), nullable=True))
        batch_op.alter_column('k_producto',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_item_k_lanzamiento_lanzamiento'), 'lanzamiento', ['k_lanzamiento'], ['id'])

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_cotizacion', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    #atencion: si ya hay lineas de pedido a la medida sin producto de catalogo, el paso de k_producto a NOT NULL fallara;
    #rescatar esos items antes de bajar la version
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('d_cotizacion')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_item_k_lanzamiento_lanzamiento'), type_='foreignkey')
        batch_op.alter_column('k_producto',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('n_item')
        batch_op.drop_column('k_lanzamiento')

    with op.batch_alter_table('solicitud_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_item_k_solicitud'))

    op.drop_table('solicitud_item')
    # ### end Alembic commands ###
