"""Agregar reserva de stock y tabla reserva_stock

Revision ID: 335967ea4b90
Revises: 67bf9fe64495
Create Date: 2026-09-27 16:25:42.952121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335967ea4b90'
down_revision = '67bf9fe64495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_invoice', sa.Integer(), nullable=False),
    sa.Column('tipo_elemento', sa.String(length=1), nullable=False),
    sa.Column('k_elemento', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('f_creacion', sa.DateTime(), nullable=False),
    sa.Column('f_expiracion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo_elemento IN ('P', 'V')", name=op.f('ck_reserva_stock_chk_tipo_elemento')),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_reserva_stock_chk_cantidad_positiva')),
    sa.ForeignKeyConstraint(['k_invoice'], ['invoice.id'], name=op.f('fk_reserva_stock_k_invoice_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserva_stock')),
    sa.UniqueConstraint('k_invoice', 'tipo_elemento', 'k_elemento', name='uq_reserva_invoice_elemento')
    )
    with op.batch_alter_table('reserva_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserva_stock_k_invoice'), ['k_invoice'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_reservado', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('stock_reservado')

    with op.batch_alter_table('reserva_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserva_stock_k_invoice'))

    op.drop_table('reserva_stock')
    # ### end Alembic commands ###
