"""url_imagen en producto

Revision ID: 34fd6248975a
Revises: 167eba4a4c5b
Create Date: 2026-09-30 21:39:00.228447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd6248975a'
down_revision = '167eba4a4c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_imagen', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('url_imagen')

    # ### end Alembic commands ###
