"""envio cotizado en solicitud

Revision ID: 353ef7b27cfb
Revises: da4b7317856e
Create Date: 2026-10-05 08:40:56.155199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353ef7b27cfb'
down_revision = 'da4b7317856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_envio_cotizado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('p_envio_cotizado')

    # ### end Alembic commands ###
