"""spotify external en lanzamiento

Revision ID: 5215e71ba6b8
Revises: 34fd6248975a
Create Date: 2026-09-30 22:41:48.683872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5215e71ba6b8'
down_revision = '34fd6248975a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_lanzamiento_external_id'), ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lanzamiento_external_id'), type_='unique')
        batch_op.drop_column('external_url')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
