"""linea base: esquema existente

Reproduce las tablas tal como estaban antes de usar migraciones (tienda + solicitudes del manager).
En una BD que ya las tiene no se ejecuta: se marca con `flask --app run db stamp 5b10cf662d03`.

Revision ID: 5b10cf662d03
Revises: 
Create Date: 2026-09-27 04:03:20.346908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b10cf662d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_artista', sa.String(length=50), nullable=False),
    sa.Column('pais_artista', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artista'))
    )
    op.create_table('categoria',
    sa.Column('k_categoria', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('k_categoria', name=op.f('pk_categoria'))
    )
    op.create_table('genero',
    sa.Column('k_genero', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('k_genero', name=op.f('pk_genero'))
    )
    op.create_table('lanzamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_lanzamiento', sa.String(length=100), nullable=False),
    sa.Column('f_lanzamiento', sa.Date(), nullable=True),
    sa.Column('i_lanzamiento', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lanzamiento'))
    )
    op.create_table('rol',
    sa.Column('k_rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('k_rol', name=op.f('pk_rol'))
    )
    op.create_table('lanzamiento__artista',
    sa.Column('k_artista', sa.Integer(), nullable=False),
    sa.Column('k_lanzamiento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['k_artista'], ['artista.id'], name=op.f('fk_lanzamiento__artista_k_artista_artista')),
    sa.ForeignKeyConstraint(['k_lanzamiento'], ['lanzamiento.id'], name=op.f('fk_lanzamiento__artista_k_lanzamiento_lanzamiento')),
    sa.PrimaryKeyConstraint('k_artista', 'k_lanzamiento', name=op.f('pk_lanzamiento__artista'))
    )
    op.create_table('lanzamiento__genero',
    sa.Column('k_genero', sa.String(length=30), nullable=False),
    sa.Column('k_lanzamiento', sa.Integer(), nullable=False),
    sa.Column('subgenre', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['k_genero'], ['genero.k_genero'], name=op.f('fk_lanzamiento__genero_k_genero_genero')),
    sa.ForeignKeyConstraint(['k_lanzamiento'], ['lanzamiento.id'], name=op.f('fk_lanzamiento__genero_k_lanzamiento_lanzamiento')),
    sa.PrimaryKeyConstraint('k_genero', 'k_lanzamiento', name=op.f('pk_lanzamiento__genero'))
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_lanzamiento', sa.Integer(), nullable=True),
    sa.Column('k_categoria', sa.String(length=30), nullable=True),
    sa.Column('n_producto', sa.String(length=100), nullable=True),
    sa.Column('p_producto', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('d_producto', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('f_producto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['k_categoria'], ['categoria.k_categoria'], name=op.f('fk_producto_k_categoria_categoria')),
    sa.ForeignKeyConstraint(['k_lanzamiento'], ['lanzamiento.id'], name=op.f('fk_producto_k_lanzamiento_lanzamiento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_rol', sa.String(length=20), nullable=True),
    sa.Column('n_usuario', sa.String(length=20), nullable=False),
    sa.Column('ape_usuario', sa.String(length=20), nullable=False),
    sa.Column('email_usuario', sa.String(length=50), nullable=False),
    sa.Column('pwd_usuario', sa.String(length=100), nullable=False),
    sa.Column('dir_usuario', sa.String(length=200), nullable=True),
    sa.Column('lugar_usuario', sa.String(length=80), nullable=True),
    sa.Column('tipo_id', sa.String(length=4), nullable=True),
    sa.Column('num_id', sa.String(length=12), nullable=True),
    sa.Column('barrio_usuario', sa.String(length=30), nullable=True),
    sa.Column('cel_usuario', sa.String(length=20), nullable=True),
    sa.Column('f_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['k_rol'], ['rol.k_rol'], name=op.f('fk_usuario_k_rol_rol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email_usuario', name=op.f('uq_usuario_email_usuario'))
    )
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_producto', sa.Integer(), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['k_producto'], ['producto.id'], name=op.f('fk_imagen_k_producto_producto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imagen'))
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_usuario', sa.Integer(), nullable=True),
    sa.Column('id_factura_payco', sa.String(length=100), nullable=True),
    sa.Column('ref_payco', sa.String(length=100), nullable=True),
    sa.Column('f_compra', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=13, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['k_usuario'], ['usuario.id'], name=op.f('fk_invoice_k_usuario_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_usuario', sa.Integer(), nullable=False),
    sa.Column('k_producto', sa.Integer(), nullable=True),
    sa.Column('n_producto_solicitado', sa.String(length=150), nullable=True),
    sa.Column('d_producto_solicitado', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('f_solicitud', sa.DateTime(), nullable=True),
    sa.Column('f_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['k_producto'], ['producto.id'], name=op.f('fk_solicitud_k_producto_producto')),
    sa.ForeignKeyConstraint(['k_usuario'], ['usuario.id'], name=op.f('fk_solicitud_k_usuario_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitud'))
    )
    op.create_table('item',
    sa.Column('k_producto', sa.Integer(), nullable=False),
    sa.Column('k_factura', sa.Integer(), nullable=False),
    sa.Column('cant_item', sa.Numeric(precision=3, scale=0), nullable=False),
    sa.Column('p_item', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['k_factura'], ['invoice.id'], name=op.f('fk_item_k_factura_invoice')),
    sa.ForeignKeyConstraint(['k_producto'], ['producto.id'], name=op.f('fk_item_k_producto_producto')),
    sa.PrimaryKeyConstraint('k_producto', 'k_factura', name=op.f('pk_item'))
    )
    # ### end Alembic commands ###

    #roles base (antes los sembraba create_app al arrancar)
    rol = sa.table('rol', sa.column('k_rol', sa.String))
    op.bulk_insert(rol, [{'k_rol': 'USER'}, {'k_rol': 'ADMIN'}, {'k_rol': 'CLIENTE'}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('solicitud')
    op.drop_table('invoice')
    op.drop_table('imagen')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('lanzamiento__genero')
    op.drop_table('lanzamiento__artista')
    op.drop_table('rol')
    op.drop_table('lanzamiento')
    op.drop_table('genero')
    op.drop_table('categoria')
    op.drop_table('artista')
    # ### end Alembic commands ###
