"""original musical box y link social del lanzamiento

Revision ID: 67bf9fe64495
Revises: f8c18145ced0
Create Date: 2026-09-27 05:36:23.905537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bf9fe64495'
down_revision = 'f8c18145ced0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_social', sa.String(length=300), nullable=True))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_mb', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('original_mb')

    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.drop_column('url_social')

    # ### end Alembic commands ###
