"""checkout sin cuenta: estado, token y envio del pedido

Aditiva: solo agrega columnas a `invoice`. Las facturas que ya existían quedan en estado PAGADO
(el flujo anterior solo guardaba pagos aceptados por ePayco) y sin token de seguimiento.

Revision ID: a36be8d1f63e
Revises: 5b10cf662d03
Create Date: 2026-09-27 04:08:34.562855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36be8d1f63e'
down_revision = '5b10cf662d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False, server_default='PENDIENTE'))
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token_creado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('n_envio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_envio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tel_envio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dir_envio', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lugar_envio', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('barrio_envio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('f_actualizacion', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_invoice_token_hash'), ['token_hash'])

    # ### end Alembic commands ###

    #datos existentes: todas las facturas previas corresponden a pagos aceptados
    op.execute("UPDATE invoice SET estado = 'PAGADO', f_actualizacion = f_compra")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_invoice_token_hash'), type_='unique')
        batch_op.drop_column('f_actualizacion')
        batch_op.drop_column('barrio_envio')
        batch_op.drop_column('lugar_envio')
        batch_op.drop_column('dir_envio')
        batch_op.drop_column('tel_envio')
        batch_op.drop_column('email_envio')
        batch_op.drop_column('n_envio')
        batch_op.drop_column('token_creado')
        batch_op.drop_column('token_hash')
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
