"""preorden en lanzamiento (paraguas para sus productos)

Revision ID: a747858d7b7a
Revises: b96fe4bbc4b7
Create Date: 2026-10-01 12:14:48.727081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a747858d7b7a'
down_revision = 'b96fe4bbc4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preorden', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanzamiento', schema=None) as batch_op:
        batch_op.drop_column('preorden')

    # ### end Alembic commands ###
