"""solicitud con contacto y cotizacion; estado de envio en ordenes

Aditiva. Datos existentes:
- solicitud: cel/email de contacto se copian del usuario asociado (k_usuario pasa a opcional).
- invoice: las PAGADAS quedan en estado_envio POR PREPARAR; las órdenes sin copia de envío
  (anteriores al checkout sin cuenta) reciben la dirección actual del usuario, para congelarla.

Revision ID: a8429ab90db1
Revises: 3c91f0d79d11
Create Date: 2026-09-27 05:00:50.209923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8429ab90db1'
down_revision = '3c91f0d79d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_envio', sa.String(length=20), nullable=True))

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cel_contacto', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_contacto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('precio_cotizado', sa.Numeric(precision=11, scale=2), nullable=True))
        batch_op.add_column(sa.Column('token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('k_invoice', sa.Integer(), nullable=True))
        batch_op.alter_column('k_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_solicitud_token_hash'), ['token_hash'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitud_k_invoice_invoice'), 'invoice', ['k_invoice'], ['id'])

    # ### end Alembic commands ###

    op.execute("""UPDATE solicitud SET
        cel_contacto = (SELECT cel_usuario FROM usuario u WHERE u.id = solicitud.k_usuario),
        email_contacto = (SELECT email_usuario FROM usuario u WHERE u.id = solicitud.k_usuario)""")
    op.execute("UPDATE invoice SET estado_envio = 'POR PREPARAR' WHERE estado = 'PAGADO'")
    op.execute("""UPDATE invoice SET
        n_envio = (SELECT trim(n_usuario || ' ' || ape_usuario) FROM usuario u WHERE u.id = invoice.k_usuario),
        email_envio = (SELECT email_usuario FROM usuario u WHERE u.id = invoice.k_usuario),
        tel_envio = (SELECT cel_usuario FROM usuario u WHERE u.id = invoice.k_usuario),
        dir_envio = (SELECT dir_usuario FROM usuario u WHERE u.id = invoice.k_usuario),
        lugar_envio = (SELECT lugar_usuario FROM usuario u WHERE u.id = invoice.k_usuario),
        barrio_envio = (SELECT barrio_usuario FROM usuario u WHERE u.id = invoice.k_usuario)
        WHERE n_envio IS NULL AND dir_envio IS NULL""")


def downgrade():
    if op.get_bind().execute(sa.text("SELECT COUNT(*) FROM solicitud WHERE k_usuario IS NULL")).scalar():
        raise RuntimeError("No se puede revertir: hay solicitudes solo con celular (sin usuario).")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_solicitud_k_invoice_invoice'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_solicitud_token_hash'), type_='unique')
        batch_op.alter_column('k_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('k_invoice')
        batch_op.drop_column('token_hash')
        batch_op.drop_column('precio_cotizado')
        batch_op.drop_column('email_contacto')
        batch_op.drop_column('cel_contacto')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('estado_envio')

    # ### end Alembic commands ###
