"""costo de envio: reglas, cache de cotizaciones y columnas de orden/producto/solicitud

Revision ID: b0db9297d9fc
Revises: 20d924a3b851
Create Date: 2026-10-02 23:14:18.938931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0db9297d9fc'
down_revision = '20d924a3b851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_dane', sa.String(length=8), nullable=False),
    sa.Column('peso_g', sa.Integer(), nullable=False),
    sa.Column('p_envio', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('carrier', sa.String(length=30), nullable=True),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('id_rate', sa.String(length=30), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotizacion_cache'))
    )
    with op.batch_alter_table('cotizacion_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizacion_cache_c_dane'), ['c_dane'], unique=False)

    op.create_table('regla_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('k_categoria', sa.String(length=30), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('total_min', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regla_envio'))
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_ubicacion', sa.String(length=80), nullable=True),
    sa.Column('c_dane', sa.String(length=8), nullable=False),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ubicacion'))
    )
    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ubicacion_n_ubicacion'), ['n_ubicacion'], unique=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_envio', sa.Numeric(precision=11, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('d_envio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('envio_manual', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('envio_carrier', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('envio_id_rate', sa.String(length=30), nullable=True))

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar_solicitud', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('lugar_solicitud')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('envio_id_rate')
        batch_op.drop_column('envio_carrier')
        batch_op.drop_column('envio_manual')
        batch_op.drop_column('d_envio')
        batch_op.drop_column('p_envio')

    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ubicacion_n_ubicacion'))

    op.drop_table('ubicacion')
    op.drop_table('regla_envio')
    with op.batch_alter_table('cotizacion_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotizacion_cache_c_dane'))

    op.drop_table('cotizacion_cache')
    # ### end Alembic commands ###
