"""preorden en producto y cantidad en solicitud

Revision ID: b96fe4bbc4b7
Revises: 5215e71ba6b8
Create Date: 2026-10-01 11:03:35.569724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96fe4bbc4b7'
down_revision = '5215e71ba6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preorden', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('preorden')

    # ### end Alembic commands ###
