"""tabla suscriptor (avisos de drops)

Revision ID: da4b7317856e
Revises: b0db9297d9fc
Create Date: 2026-10-03 11:44:06.495451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4b7317856e'
down_revision = 'b0db9297d9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscriptor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.Column('f_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suscriptor'))
    )
    with op.batch_alter_table('suscriptor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suscriptor_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscriptor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suscriptor_email'))

    op.drop_table('suscriptor')
    # ### end Alembic commands ###
