"""Add mp_payment_id field to Invoice model

Revision ID: e0ea8222558e
Revises: 335967ea4b90
Create Date: 2026-09-29 15:32:25.673639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ea8222558e'
down_revision = '335967ea4b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_payment_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('mp_payment_id')

    # ### end Alembic commands ###
