"""mensaje del cliente en solicitud

Revision ID: ebf0436edd8d
Revises: 353ef7b27cfb
Create Date: 2026-10-05 10:30:26.768296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf0436edd8d'
down_revision = '353ef7b27cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_mensaje_cliente', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('d_mensaje_cliente')

    # ### end Alembic commands ###
