"""redes sociales en el inicio y configuracion del sitio

Revision ID: f8c18145ced0
Revises: a8429ab90db1
Create Date: 2026-09-27 05:09:11.734822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c18145ced0'
down_revision = 'a8429ab90db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('f_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('clave', name=op.f('pk_configuracion'))
    )
    op.create_table('publicacion_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('id_externo', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('error_embed', sa.String(length=200), nullable=True),
    sa.Column('f_creacion', sa.DateTime(), nullable=True),
    sa.Column('f_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publicacion_social')),
    sa.UniqueConstraint('plataforma', 'id_externo', name='uq_publicacion_social_plataforma_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicacion_social')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
